apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-llm
  template:
    metadata:
      labels:
        app: model-llm
    spec:
      containers:
        - name: model-llm
          image: conecta/model-llm:latest
          ports:
            - containerPort: 8002

---
apiVersion: v1
kind: Service
metadata:
  name: model-llm
spec:
  selector:
    app: model-llm
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: ClusterIP
